### ISSUE TITLE
ncdu instead of du-tool.sh [Info, not an Issue.]

### ISSUE THREAD

**Issue by juergen852** [theCalcaholic/bash-utils#1]
Congrats on you nice collection of scripts !

As I saw your du-tool.sh:  Are you aware of "ncdu" ?
- apt install ncdu 

Took me years to find this, maybe it is also interesting for you.
It always starts in current directory, navigation into subdirs with up and down + enter.
Example of my /root :

ncdu 1.15.1 ~ Use the arrow keys to navigate, press ? for help                                                                                                                                         
--- /root -------------------------------------------------------------
  384,9 MiB [##########] /.vscode-server                                                                                                                                                               
  380,0 MiB [######### ]  output_file
  204,4 MiB [#####     ] /skripte
  140,9 MiB [###       ]  output_file_4th_test
    8,5 MiB [          ] /.ansible
    6,7 MiB [          ]  junk.ndb
    4,0 MiB [          ]  check-mk-agent_2.1.0p26-d519c72aa6040cd4_all.deb
    2,2 MiB [          ] /.launchpadlib
  412,0 KiB [          ] /snap
  364,0 KiB [          ] /docker-onlyoffice-nextcloud
  220,0 KiB [          ]  .bash_history

Best Regards

**Comment by theCalcaholic** [comment]
Thanks, might check it out :)
